### ISSUE TITLE
Implement birthdays

### ISSUE THREAD

**Issue by jaysella** [nu25/hoosky-bot#13]
## Description

Users can add their birthday. Each day, the bot checks the database for any birthdays and sends a message.

## Proposed Commands

- `/birthday set [date]`: Set a user's birthday
- `/birthday unset`: Clear a user's birthday
- `/birthday show [user]`: Show a user's birthday
- `/birthday list`: List all user's birthdays in a message visible only to the user

## Tasks

- [x] Implement core logic
- [x] Explore how to check database daily
- [x] Create set of birthday greetings
- [x] Add a command allowing Mods to configure the `#birthday` channel?

## Questions

1. If there are multiple birthdays on the same day, should all be combined into one message or a unique message for each?
2. How to check database daily and trigger message?
3. Should the set of birthday messages be configurable by mods? Eg `/birthday message add [msg]` `/birthday message remove [msg]`?

**Comment by cassanof** [comment]
I actually ran before into implementing something similar, so I think I can give an idea of how we would store/retrieve birthdays:
 - Create a separate collection for birthdays
 - Create a different document for birthdays, and every birthday needs to have an unique-id (along with the user info, day, etc..)
 - Create a main document with inside an hashmap holding as key value every day of the year (from 1 to 366) and set a value for every key as list (not an array, as we would need to add to the list) of the unique id (or a reference, which is better but harder to implement) of each user's birthday.
 - Everyday we just access the hashmap's key that's the same as the day of the year and retreive the singular users from there.

This is a sketch of how the database design might look like:

 * Birthdays (collection):
    - refs (document with the hashmap):
      - `map = {'1'...'366': '{uuid-34343-54334-fddf}...'}`
    - joe (document of a person's birthday):
      - name
      - uuid
      - birthday message
      - other stuff...

EDIT:
btw, we can actually use discord's user's id (eg: 193135946374316032) so that then we can retrieve the user's information from discord instead of storing it ourselves.
