### ISSUE TITLE
Implement starboards

### ISSUE THREAD

**Issue by aiyan** [nu25/hoosky-bot#3]
### Description

Users can react to any message with a :star:. After enough reactions are accumulated, the message is saved into the configured channel. Mods can configure the reaction count threshold.

### Tasks

- [x] After every new reaction, check the number of :star:'s, and deposit the message in the starboard channel if the threshold is passed.
- [ ] Add a command allowing Mods to configure the reaction count threshold.
- [ ] Add a command allowing Mods to configure the reaction (:star:/:heart:/🤮) and corresponding channel.

**Comment by jaysella** [comment]
Anyboard implemented in commits up to and including https://github.com/neu25/hoosky-bot/commit/2cff9dd41ceda09d4d5fc902ac4d6dd86d4a0318
